import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Container from '../components/Container';
import styled from 'styled-components'
import client from '../client'
import { ITeamMember } from '../types'
import Directory from '../components/Directory';

const StyledPageTitle = styled.h1`
  font-size: 7rem;
  line-height: 1.1;
  font-weight: 900;
  color: var(--primary-color);
`

const DirectoryWrapper = styled.div`
  margin: 6rem 0;
`

export default function About({ teamMembers, departments }: { teamMembers: ITeamMember[], departments: string[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Container>
          <StyledPageTitle>What is Served With Honor?</StyledPageTitle>
          <p>Proudly Serving Those Who Served!</p>
          <p>We&apos;re on a mission to help 10M+ veterans and their families live Happier, Healthier, and Wealthier lives.</p>
          <p>Served With Honor is the parent company of:</p>
          <ul>
            <li><a href="https://vaclaimsinsider.com/" target="_blank" rel="noreferrer">VA Claims Insider</a></li>
            <li><a href="https://telemedicallc.com/" target="_blank" rel="noreferrer">Telemedica</a></li>
            <li><a href="https://militarydisabilitymadeeasy.com/" target="_blank" rel="noreferrer">Military Disability Made Easy</a></li>
            <li><a href="https://lendherohomeloans.com/" target="_blank" rel="noreferrer">LendHero Home Loans</a></li>
            <li><a href="https://hireveterans.com/" target="_blank" rel="noreferrer">HireVeterans</a></li>
            <li><a href="https://rawcider.com/" target="_blank" rel="noreferrer">RAW Cider Company</a></li>
          </ul>
          <DirectoryWrapper>
            <Directory members={teamMembers} departments={departments} />
          </DirectoryWrapper>
        </Container>
      </main>
      <Footer />
    </>
  )
}

export async function getServerSideProps(context: any) {
  // Get all Team Members and list of Departments
  let { teamMembers, departments } = await client.fetch(`{
    "teamMembers": *[_type == "teamMember"] | order(orderRank) {
      first_name,
      last_name,
      prefered_name,
      position,
      "department": department->name,
      image {
					asset->{
						...,
						metadata
					}
				},
    },
    "departments": *[_type == "department"] | order(orderRank){ name }
  }`);
  
  // Modify team members to use prefered name if present
  teamMembers = teamMembers.map((person: any) => {
    const name = `${person.prefered_name ? person.prefered_name : person.first_name} ${person.last_name}`
    person.name = name;
    delete person.first_name;
    delete person.last_name;
    delete person.prefered_name;
    return person;
  });
  
  departments = departments.map((a: { name: string }) => a.name);
  
  return { props: { teamMembers, departments } };
}
